In [2]:
import numpy as np
x = [50, 720]
w = [0.01, 0.002]
b = -5
z = np.dot(w,x) + b
print(z)

-3.06


In [34]:
def sigma(x):
    return 1/(1+np.power(np.e, -x))

In [35]:
X=[[4,100,0], [1,50,1], [10,200,0]]
w = [0.2, -0.01, 1.5]
b = -2

print(sigma(np.dot(X,w) + b))


[0.09975049 0.31002552 0.11920292]


In [36]:
X = [[2, 70], [5,80], [8,90]]
w = [0.5, 0.05]
b = -6

print(sigma(np.dot(X,w) + b))

[0.18242552 0.62245933 0.92414182]


In [42]:
X = [[8, 2, 2], [3, 6, 1.5], [6, 1, 2.5]]
w = [1.2, 0.1, -0.8]
b = -0.5

result = sigma(np.dot(X,w) + b)
print(result)
predictions = (result >= 0.5).astype(int)
print("Liked (yes = 1, no = 0):", predictions)

[0.99954738 0.92414182 0.99183743]
Liked (yes = 1, no = 0): [1 1 1]


In [41]:
X = [50, 28, 130]
w = [0.03, 0.08, 0.01]
b = -7

print(sigma(np.dot(X,w) + b))

0.12346704756522399
