In [8]:
import numpy as np

arr = np.array([16, 12, 85])
print(arr)

[16 12 85]


In [11]:
arr_two = np.array([[16,12,95],[17, 10, 78],[15,14,90]])
print(arr_two)
print("shape:", arr_two.shape)

[[16 12 95]
 [17 10 78]
 [15 14 90]]
shape: (3, 3)


In [12]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a+b)

[ 3  7 11]


In [13]:
print(a*b)

[ 2 12 30]


In [15]:
x = [2,3]
w = [0.5, 0.8]

print(np.dot(x, w))

3.4000000000000004


In [17]:
b = 1.2
y_hat = np.dot(x, w) + b
print(y_hat)

4.6000000000000005


In [18]:
X = ([[1,2], [3,4], [5,6], [7,8]])
weight = ([[0.1], [0.2]])

result = np.matmul(X, weight)
print(result)

[[0.5]
 [1.1]
 [1.7]
 [2.3]]
